# Generated by Django 4.2.5 on 2023-09-21 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
                ('recipe', models.TextField(blank=True, max_length=200, verbose_name='Рецепт')),
                ('image', models.ImageField(upload_to='dishes_images', verbose_name='Картинка')),
                ('is_free', models.BinaryField(default=False, verbose_name='Бесплатное')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название ингредиента')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Количество калорий')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тип приема пищи',
                'verbose_name_plural': 'Типы приемов пищи',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания подписки')),
                ('expires_at', models.DateTimeField(verbose_name='Дата истечения подписки')),
                ('portion_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество персон')),
                ('allergies', models.ManyToManyField(blank=True, null=True, related_name='allergy_subscriptions', to='baseapp.mealtype', verbose_name='Аллергии')),
                ('meal_types', models.ManyToManyField(blank=True, null=True, related_name='subscriptions', to='baseapp.mealtype', verbose_name='Типы приемов пищи')),
                ('today_dishes', models.ManyToManyField(blank=True, null=True, related_name='dish_subscriptions', to='baseapp.dish', verbose_name='Сегодняшние блюда подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('dish', models.ManyToManyField(related_name='type_of_menu', to='baseapp.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Вид диеты',
                'verbose_name_plural': 'Виды диеты',
            },
        ),
        migrations.CreateModel(
            name='DishIngredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиента')),
                ('measurement', models.CharField(max_length=50, verbose_name='Мера ингредиента')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_items', to='baseapp.dish', verbose_name='Блюдо')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_items', to='baseapp.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент в блюде',
                'verbose_name_plural': 'Ингредиенты в блюде',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='baseapp.mealtype', verbose_name='Тип приема пищи'),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('ingredients', models.ManyToManyField(related_name='allergies', to='baseapp.ingredient', verbose_name='Подходящие ингредиенты')),
            ],
        ),
    ]
