# Generated by Django 4.2.5 on 2023-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_subscription_is_paid_subscription_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_category_images', verbose_name='Картинка'),
        ),
    ]
