# Generated by Django 4.2.5 on 2023-09-23 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_menucategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='menu_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='baseapp.menucategory', verbose_name='Категория меню'),
        ),
    ]
