# Generated by Django 4.2.5 on 2023-09-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_merge_20230924_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='menu_category',
            new_name='menu_categories',
        ),
    ]
